import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/transaction.dart';

class ExportService {
  static Future<void> exportToCsv(List<Transaction> transactions) async {
    // 1. Prepare Data manually to avoid package issues
    StringBuffer csvBuffer = StringBuffer();
    
    // Add Header
    csvBuffer.writeln('Date,Title,Amount,Category,Type');
    
    for (var tx in transactions) {
      String date = DateFormat('yyyy-MM-dd').format(tx.date);
      // Simple escaping for CSV: wrap in quotes if contains comma
      String title = tx.title.contains(',') ? '"${tx.title}"' : tx.title;
      String type = tx.isIncome ? 'Income' : 'Expense';
      
      csvBuffer.writeln('$date,$title,${tx.amount},${tx.category},$type');
    }

    // 2. Save & Share
    try {
      final directory = await getTemporaryDirectory();
      final path = '${directory.path}/transactions_export_${DateTime.now().millisecondsSinceEpoch}.csv';
      final file = File(path);
      
      await file.writeAsString(csvBuffer.toString());
      
      // Share the file
      await Share.shareXFiles([XFile(path)], text: 'My Money Manager Export');
    } catch (e) {
      rethrow;
    }
  }

  static Future<void> exportMonthlyReport(List<Transaction> transactions) async {
    final now = DateTime.now();
    final thisMonthTxs = transactions.where((t) => 
      t.date.month == now.month && t.date.year == now.year
    ).toList();

    double totalIncome = thisMonthTxs.where((t) => t.isIncome).fold(0, (sum, t) => sum + t.amount);
    double totalExpense = thisMonthTxs.where((t) => !t.isIncome).fold(0, (sum, t) => sum + t.amount);
    
    // Find top category
    Map<String, double> categories = {};
    for (var tx in thisMonthTxs.where((t) => !t.isIncome)) {
      categories[tx.category] = (categories[tx.category] ?? 0) + tx.amount;
    }
    
    String topCategory = 'None';
    double maxAmount = 0;
    categories.forEach((k, v) {
      if (v > maxAmount) {
        maxAmount = v;
        topCategory = k;
      }
    });

    String report = '''
Monthly Financial Report - ${DateFormat('MMMM yyyy').format(now)}
-------------------------------------------
Total Income:   \$${totalIncome.toStringAsFixed(2)}
Total Expense:  \$${totalExpense.toStringAsFixed(2)}
Net Balance:    \$${(totalIncome - totalExpense).toStringAsFixed(2)}
-------------------------------------------
Top Spending Category: $topCategory (\$${maxAmount.toStringAsFixed(2)})
-------------------------------------------
Generated by Money Manager
''';

    try {
      final directory = await getTemporaryDirectory();
      final path = '${directory.path}/monthly_report_${now.month}_${now.year}.txt';
      final file = File(path);
      
      await file.writeAsString(report);
      await Share.shareXFiles([XFile(path)], text: 'Monthly Financial Report');
    } catch (e) {
      rethrow;
    }
  }
}
